### ISSUE TITLE
"(B|E|T)-Mult" are not highlighted

### ISSUE THREAD

**Issue by ghost** [kitagawa-hr/vscode-copl#1]
Derivation Rules of `B-Mult`, `E-Mult` and `T-Mult` are not highlighted.
`T-Mult` is a rule of PolyTypingML4.
`E-Mult` and `B-Mult` are rules of EvalRefML3.
These rules may be in `master/src/extension.ts`

**Comment by kitagawa-hr** [comment]
closed by #2
